#!/bin/zsh

echo "Which Do you create? a(article)/b(book) (default article)"
target=""

while true; do
  read type
  if [[ $type == "b" ]] || [[ $type == "book" ]]; then
    target="book"
    echo "you will create a book!"
    break
  elif [[ $type == "a" ]] || [[ $type == "article" ]] || [[ $type == "" ]]; then
    target="article"
    echo "you will create a article!"
    break
  else
    echo "please select article(a) or book(b)"
  fi
done

echo "please input slug. restrict: ^[0-9a-z-_]{12,50}$"
echo "if slug is empty, slug will be generated as random string."
read slug

if [ -z "$slug" ]; then
  npx zenn new:$target
else
  npx zenn new:$target --slug $slug
fi

if [[ $target == "article" ]]; then
  echo "## この記事は" >> articles/$slug.md
  echo "" >> articles/$slug.md
  echo "## 参考" >> articles/$slug.md
fi

